
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-cpp:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: zypper --non-interactive install alsa-devel kernel-default yast2 yast2-ruby-bindings yast2-testsuite

    - name: Package Build
      run: yast-ci-cpp

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:  [ "tumbleweed", "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: POT Check
      run: rake check:pot

    - name: Syntax Check
      run: rake check:syntax
